jobs:
  - job: Test
    pool:
      vmImage: "macOS 10.13"
    steps:
      - task: NodeTool@0
        displayName: "Use Node 8.x"
        inputs:
          versionSpec: 8.x
      - script: "yarn install"
        displayName: "yarn install"
      - script: |
          yarn global add codacy-coverage
          yarn test --ci --reporters=jest-junit --testFailureExitCode=0 --coverage
          cat ./coverage/lcov.info | codacy-coverage -n vpsny
        displayName: "yarn test"
        env:
          JEST_JUNIT_OUTPUT: ./artifacts/junit.xml
      - task: PublishTestResults@2
        displayName: "Publish Test Results"
        inputs:
          testResultsFiles: artifacts/junit.xml
      - task: PublishCodeCoverageResults@1
        displayName: "Publish Code Coverage"
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: "$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml"
          reportDirectory: "$(System.DefaultWorkingDirectory)/coverage"

  - job: Build
    pool: Default
    steps:
      - task: NodeTool@0
        displayName: "Use Node 8.x"
        inputs:
          versionSpec: 8.x
      - script: "yarn install"
        displayName: "yarn install"
      - script: |
          bundle install --retry=3 --jobs=4
        displayName: "bundle install"
      - task: DownloadSecureFile@1
        inputs:
          secureFile: "f5892e40-bdec-4732-89c8-800d4a42f32b"
      - script: |
          bundle exec fastlane setup_signing
        displayName: "Install Certificate"
      - script: |
          # 防止 fastlane/keys 不存在, 导致失败。
          touch fastlane/keys
          bundle exec fastlane beta skip_metadata:true only_build:true
        displayName: "Build IOS"
