# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: "macOS 10.13"
strategy:
  matrix:
    node_8_x:
      node_version: 8.x
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
  # - task: Xcode@5
  #   inputs:
  #     sdk: "iphoneos"
  #     configuration: "Release"
  #     xcodeVersion: "10"
  - script: |
      gem install bundler
      bundle install --retry=3 --jobs=4
    displayName: "bundle install"
  - script: |
      yarn install
    displayName: "yarn install"
  - task: InstallSSHKey@0
    inputs:
      hostName: ""
      sshPublicKey: ""
      sshKeySecureFile: gitlab
  - script: |
      bundle exec fastlane setup_signing
    displayName: "sync code signing"
  # - script: |
  #     bundle exec fastlane beta skip_metadata:true only_build:true
  #   displayName: "fastlane beta"
  # - task: Xcode@5
  #   inputs:
  #     actions: 'build'
  #     scheme: ''
  #     sdk: 'iphoneos'
  #     configuration: 'Release'
  #     xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
  #     xcodeVersion: 'default' # Options: 8, 9, default, specifyPath
