pool:
  vmImage: "macOS 10.13"

steps:
  - task: NodeTool@0
    displayName: "Use Node 8.x"
    inputs:
      versionSpec: 8.x

  - script: "yarn install"
    displayName: "yarn install"

  - script: |
      yarn global add codacy-coverage
      yarn test --ci --reporters=default --reporters=jest-junit --testFailureExitCode=0
      cat ./coverage/lcov.info | codacy-coverage -t a4b375679625458e83026a0469e18cb7 -n vpsny
    displayName: "yarn test"
    env:
      JEST_JUNIT_OUTPUT: ./artifacts/junit.xml

  - task: PublishTestResults@2
    displayName: "Publish Test Results artifacts/junit.xml"
    inputs:
      testResultsFiles: artifacts/junit.xml
