# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'vpser' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # React-native
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTAnimation',
    'RCTNetwork',
    'RCTActionSheet',
    'CxxBridge',
    'RCTBlob',
    'RCTWebSocket',
    'RCTImage',
    'DevSupport',
    'RCTVibration',
    'RCTGeolocation',
    'RCTSettings',
    'RCTPushNotification',
    'RCTLinkingIOS'
  ]

  # React-native-vector-icons
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  # React-native-i18n
  pod 'RNI18n', :path => '../node_modules/react-native-i18n'
  # React-native-splash-screen
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  # BVLinearGradient
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  # RNSVG
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  # Spinkit
  pod 'react-native-spinkit', :path => '../node_modules/react-native-spinkit'
  # RNDeviceInfo
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  # RNSSHClient
  pod 'RNSSHClient', :path => '../node_modules/react-native-ssh-sftp'
  # React-native-sound
  pod 'RNSound', :path => '../node_modules/react-native-sound'
  # RNFabric
  pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'
  # NMSSH
  pod 'NMSSH'
  # Fabric
  pod 'Fabric'
  pod 'Crashlytics'

end
