# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
min_fastlane_version('2.73.0')

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id '10696c64-ce3d-48da-b71b-5ad26e08af52'

default_platform :ios

platform :ios do
  before_all do
    ENV['CERTIFICATES_GIT_URL'] = 'git@gitlab.com:homeworld.life/certificates.git'
    ENV['DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS'] = '-t DAV'
    ENV['FASTLANE_ITUNES_TRANSPORTER_USE_SHELL_SCRIPT'] = '1'
  end

  def load_keys
    import('keys')
  rescue StandardError => exception
    UI.error('fastlane/keys file not found. To use this Fastfile, copy fastlane/keys.template into fastlane/keys and fill in the values')
    raise exception
  end

  def change_log_since_last_tag
    # http://git-scm.com/docs/pretty-formats
    # <short hash> <commit title>
    last_tag = sh("git describe --abbrev=0 --tags").strip!
    changelog_from_git_commits(
      pretty: '%h %s',
      commits_count: [sh("git cherry #{last_tag} | wc -l").to_i, 10].min,
      date_format: 'short',
      match_lightweight_tag: false,
      merge_commit_filtering: 'exclude_merges'
    )
  end

  def version_string(version_number, build_number)
    "#{version_number} (#{build_number})"
  end

  desc '获取最新的 证书 与 配置文件'
  lane :setup_signing do
    keychain_name = ENV['KEYCHAIN_NAME']
    keychain_password = ENV['KEYCHAIN_PASSWORD']
    git_url = ENV['CERTIFICATES_GIT_URL']
    sync_code_signing(
      git_url: git_url,
      app_identifier: 'life.homeworld.app.vpser',
      keychain_name: keychain_name,
      keychain_password: keychain_password,
      type: 'development',
      clone_branch_directly: true,
      readonly: true
    )
    sync_code_signing(
      git_url: git_url,
      app_identifier: 'life.homeworld.app.vpser',
      keychain_name: keychain_name,
      keychain_password: keychain_password,
      type: 'appstore',
      clone_branch_directly: true,
      readonly: true
    )
  end

  desc '自动截图'
  lane :screenshots do
    # load_keys
    capture_screenshots
    frame_screenshots
  end

  lane :update_metadata do
    load_keys

    deliver(
      app_version: '0.0.7'
    )
  end

  desc 'Runs all the tests'
  lane :test do
    scan(
      workspace: './ios/vpsny.xcworkspace',
      devices: ['iPhone X']
    )
  end

  desc '提交一个新的测试版本 Apple TestFlight'
  lane :beta do |options|
    load_keys

    only_build = options[:only_build]
    skip_build = options[:skip_build]

    unless only_build
      unless skip_build

        ensure_git_status_clean

        pre_version_number = get_version_number(xcodeproj: './ios/vpsny.xcodeproj')

        version_number = options[:version_number]

        if version_number.nil?
          # Get the recent tags of the branch as the version number
          version_number = (sh 'git describe --tags --abbrev=0').gsub(/^[v]/, '').chomp
        end

        increment_version_number(
          version_number: version_number,
          xcodeproj: './ios/vpsny.xcodeproj'
        )
        # Get testflight build_number + 1
        # initial_build_number = get_build_number(xcodeproj: './ios/vpsny.xcodeproj')
        build_number = latest_testflight_build_number + 1
        increment_build_number(
          build_number: build_number,
          xcodeproj: './ios/vpsny.xcodeproj'
        )
        complete_version_number = version_string(version_number, build_number)

        change_log = change_log_since_last_tag

        skip_metadata = options[:skip_metadata]

        if skip_metadata == true
          UI.message('Skipping taking screenshots and uploading metadata'.green)
        else
          clear_derived_data
          screenshots
          update_metadata
        end

      end
    end

    unless skip_build
      clean_build_artifacts
      clear_derived_data

      cocoapods(podfile: './ios/Podfile')
      build_app(
        scheme: 'vpsny',
        workspace: './ios/vpsny.xcworkspace',
        configuration: 'Release',
        output_directory: './ios/build',
        silent: true,
        clean: true
      )
    end

    unless only_build
      testflight(
        ipa: './ios/build/vpsny.ipa',
        changelog: change_log,
        skip_submission: true,
        distribute_external: false,
        beta_app_feedback_email: 'limaofeng@msn.com',
        beta_app_description: 'vpsny can help you manage your vps, support vultr'
      )

      slack(
        message: "Submitted build of vpsny to TestFlight: v#{complete_version_number}",
        channel: '#general'
      )
    end

    rocket
  end

  desc '部署一个新版本到 App Store'
  lane :release do
    appstore(force: true)
  end

  # If the weekly task fails, then ship a message, a success would also send
  error do |_, exception|
    slack(message: "Error Deploying Emission: #{exception}",
          success: false,
          payload: { Output: exception.error_info.to_s })
  end
end
