# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 6s",
  # "iPhone 6s Plus",
  # "iPhone 7",
  # "iPhone 7 Plus",
  # "iPhone 8",
  # "iPhone 8 Plus",
  # "iPhone X",
])

languages([
  "zh-Hans"
])

# The name of the scheme which contains the UI Tests
scheme "vpsny"

configuration "Release"

# Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots"

# clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
# project "./ios/vpsny.xcodeproj"
workspace "./ios/vpsny.xcworkspace"

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments([
#   "-secretFeatureEnabled YES",
#   "-secretFeatureEnabled NO"
# ])

# For more information about all available options run
clean false
skip_open_summary true
output_simulator_logs true
clear_previous_screenshots true
